package Freelance.bean;
// Generated Jan 11, 2021, 7:47:13 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", schema = "dbo", catalog = "freelance", uniqueConstraints = @UniqueConstraint(columnNames = "acc"))
public class Account implements java.io.Serializable {

	private Integer id;
	private Serializable acc;
	private Serializable pass;
	private RatingFa ratingFa;
	private Set<JobsUser> jobsUsers = new HashSet<JobsUser>(0);
	private Set<Rating> ratingsForId = new HashSet<Rating>(0);
	private Set<Jobs> jobses = new HashSet<Jobs>(0);
	private Users users;
	private Set<Favorites> favoriteses = new HashSet<Favorites>(0);
	private Set<Rating> ratingsForUserId = new HashSet<Rating>(0);
	private Set<UserSkill> userSkills = new HashSet<UserSkill>(0);

	public Account() {
	}
	
	public Account(String acc, String pass) {
		this.acc = acc;
		this.pass = pass;
	}

	public Account(Serializable acc, Serializable pass, RatingFa ratingFa, Set<JobsUser> jobsUsers,
			Set<Rating> ratingsForId, Set<Jobs> jobses, Users users, Set<Favorites> favoriteses,
			Set<Rating> ratingsForUserId, Set<UserSkill> userSkills) {
		this.acc = acc;
		this.pass = pass;
		this.ratingFa = ratingFa;
		this.jobsUsers = jobsUsers;
		this.ratingsForId = ratingsForId;
		this.jobses = jobses;
		this.users = users;
		this.favoriteses = favoriteses;
		this.ratingsForUserId = ratingsForUserId;
		this.userSkills = userSkills;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "acc", unique = true)
	public Serializable getAcc() {
		return this.acc;
	}

	public void setAcc(Serializable acc) {
		this.acc = acc;
	}

	@Column(name = "pass")
	public Serializable getPass() {
		return this.pass;
	}

	public void setPass(Serializable pass) {
		this.pass = pass;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "account")
	public RatingFa getRatingFa() {
		return this.ratingFa;
	}

	public void setRatingFa(RatingFa ratingFa) {
		this.ratingFa = ratingFa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<JobsUser> getJobsUsers() {
		return this.jobsUsers;
	}

	public void setJobsUsers(Set<JobsUser> jobsUsers) {
		this.jobsUsers = jobsUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountById")
	public Set<Rating> getRatingsForId() {
		return this.ratingsForId;
	}

	public void setRatingsForId(Set<Rating> ratingsForId) {
		this.ratingsForId = ratingsForId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Jobs> getJobses() {
		return this.jobses;
	}

	public void setJobses(Set<Jobs> jobses) {
		this.jobses = jobses;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "account")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<Favorites> getFavoriteses() {
		return this.favoriteses;
	}

	public void setFavoriteses(Set<Favorites> favoriteses) {
		this.favoriteses = favoriteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "accountByUserId")
	public Set<Rating> getRatingsForUserId() {
		return this.ratingsForUserId;
	}

	public void setRatingsForUserId(Set<Rating> ratingsForUserId) {
		this.ratingsForUserId = ratingsForUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "account")
	public Set<UserSkill> getUserSkills() {
		return this.userSkills;
	}

	public void setUserSkills(Set<UserSkill> userSkills) {
		this.userSkills = userSkills;
	}

}
