package Freelance.bean;
// Generated Jan 7, 2021, 1:26:51 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cagetory generated by hbm2java
 */
@Entity
@Table(name = "cagetory", schema = "dbo", catalog = "freelance")
public class Cagetory implements java.io.Serializable {

	private Integer id;
	private Serializable linhVuc;
	private Set<JobCagetory> jobCagetories = new HashSet<JobCagetory>(0);

	public Cagetory() {
	}

	public Cagetory(Serializable linhVuc, Set<JobCagetory> jobCagetories) {
		this.linhVuc = linhVuc;
		this.jobCagetories = jobCagetories;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "linh_vuc")
	public Serializable getLinhVuc() {
		return this.linhVuc;
	}

	public void setLinhVuc(Serializable linhVuc) {
		this.linhVuc = linhVuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cagetory")
	public Set<JobCagetory> getJobCagetories() {
		return this.jobCagetories;
	}

	public void setJobCagetories(Set<JobCagetory> jobCagetories) {
		this.jobCagetories = jobCagetories;
	}

}
