package Freelance.bean;
// Generated Jan 7, 2021, 1:26:51 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Favorites generated by hbm2java
 */
@Entity
@Table(name = "favorites", schema = "dbo", catalog = "freelance")
public class Favorites implements java.io.Serializable {

	private FavoritesId id;
	private Account account;
	private Jobs jobs;

	public Favorites() {
	}

	public Favorites(FavoritesId id) {
		this.id = id;
	}

	public Favorites(FavoritesId id, Account account, Jobs jobs) {
		this.id = id;
		this.account = account;
		this.jobs = jobs;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id")),
			@AttributeOverride(name = "jobId", column = @Column(name = "job_id")) })
	public FavoritesId getId() {
		return this.id;
	}

	public void setId(FavoritesId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "user_id", insertable = false, updatable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "job_id", insertable = false, updatable = false)
	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

}
