package Freelance.bean;
// Generated Jan 7, 2021, 1:26:51 AM by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * JobsSkill generated by hbm2java
 */
@Entity
@Table(name = "jobs_skill", schema = "dbo", catalog = "freelance")
public class JobsSkill implements java.io.Serializable {

	private JobsSkillId id;
	private Jobs jobs;
	private Skills skills;

	public JobsSkill() {
	}

	public JobsSkill(JobsSkillId id) {
		this.id = id;
	}

	public JobsSkill(JobsSkillId id, Jobs jobs, Skills skills) {
		this.id = id;
		this.jobs = jobs;
		this.skills = skills;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "skillId", column = @Column(name = "skill_id")) })
	public JobsSkillId getId() {
		return this.id;
	}

	public void setId(JobsSkillId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", insertable = false, updatable = false)
	public Jobs getJobs() {
		return this.jobs;
	}

	public void setJobs(Jobs jobs) {
		this.jobs = jobs;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "skill_id", insertable = false, updatable = false)
	public Skills getSkills() {
		return this.skills;
	}

	public void setSkills(Skills skills) {
		this.skills = skills;
	}

}
