package Freelance.bean;
// Generated Jan 7, 2021, 1:26:51 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name = "jobs", schema = "dbo", catalog = "freelance")
public class Jobs implements java.io.Serializable {

	private Integer id;
	private Account account;
	private JobCagetory jobCagetory;
	private Serializable ten;
	private Serializable thongTin;
	private Date hanChot;
	private String nganSachTu;
	private String nganSachDen;
	private Boolean hoanThanh;
	private Set<JobsSkill> jobsSkills = new HashSet<JobsSkill>(0);
	private Set<Favorites> favoriteses = new HashSet<Favorites>(0);
	private Set<JobsUser> jobsUsers = new HashSet<JobsUser>(0);

	public Jobs() {
	}
	public Jobs(Jobs another) {
		this.id = another.id;
		this.account = another.getAccount();
		this.jobCagetory = another.getJobCagetory();
		this.ten = another.getTen();
		this.thongTin = another.getThongTin();
		this.hanChot = another.getHanChot();
		this.nganSachTu = another.getNganSachTu();
		this.nganSachDen = another.getNganSachDen();
		this.hoanThanh = another.getHoanThanh();
		this.jobsSkills = another.getJobsSkills();
		this.favoriteses = another.getFavoriteses();
		this.jobsUsers = another.getJobsUsers();
	}
	
	public Jobs(Account account) {
		this.account = account;
		this.hoanThanh = false;
		this.ten = "";
		this.thongTin = "";
		this.hanChot = new Date();
	}

	public Jobs(Account account, JobCagetory jobCagetory, Serializable ten, Serializable thongTin, Date hanChot,
			String nganSachTu, String nganSachDen, Boolean hoanThanh, Set<JobsSkill> jobsSkills, Set<Favorites> favoriteses,
			Set<JobsUser> jobsUsers) {
		this.account = account;
		this.jobCagetory = jobCagetory;
		this.ten = ten;
		this.thongTin = thongTin;
		this.hanChot = hanChot;
		this.nganSachTu = nganSachTu;
		this.nganSachDen = nganSachDen;
		this.hoanThanh = hoanThanh;
		this.jobsSkills = jobsSkills;
		this.favoriteses = favoriteses;
		this.jobsUsers = jobsUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "ntd_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "loai_cong_viec")
	public JobCagetory getJobCagetory() {
		return this.jobCagetory;
	}

	public void setJobCagetory(JobCagetory jobCagetory) {
		this.jobCagetory = jobCagetory;
	}

	@Column(name = "ten")
	public Serializable getTen() {
		return this.ten;
	}

	public void setTen(Serializable ten) {
		this.ten = ten;
	}

	@Column(name = "thong_tin")
	public Serializable getThongTin() {
		return this.thongTin;
	}

	public void setThongTin(String thongTin) {
		this.thongTin = thongTin;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "han_chot", length = 23)
	public Date getHanChot() {
		return this.hanChot;
	}

	public void setHanChot(Date hanChot) {
		this.hanChot = hanChot;
	}

	@Column(name = "ngan_sach_tu")
	public String getNganSachTu() {
		return this.nganSachTu;
	}

	public void setNganSachTu(String nganSachTu) {
		this.nganSachTu = nganSachTu;
	}

	@Column(name = "ngan_sach_den")
	public String getNganSachDen() {
		return this.nganSachDen;
	}

	public void setNganSachDen(String nganSachDen) {
		this.nganSachDen = nganSachDen;
	}

	@Column(name = "hoan_thanh")
	public Boolean getHoanThanh() {
		return this.hoanThanh;
	}

	public void setHoanThanh(Boolean hoanThanh) {
		this.hoanThanh = hoanThanh;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "jobs")
	public Set<JobsSkill> getJobsSkills() {
		return this.jobsSkills;
	}

	public void setJobsSkills(Set<JobsSkill> jobsSkills) {
		this.jobsSkills = jobsSkills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<Favorites> getFavoriteses() {
		return this.favoriteses;
	}

	public void setFavoriteses(Set<Favorites> favoriteses) {
		this.favoriteses = favoriteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsUser> getJobsUsers() {
		return this.jobsUsers;
	}

	public void setJobsUsers(Set<JobsUser> jobsUsers) {
		this.jobsUsers = jobsUsers;
	}

}
