package Freelance.bean;
// Generated Jan 11, 2021, 8:13:39 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Rating generated by hbm2java
 */
@Entity
@Table(name = "rating", schema = "dbo", catalog = "freelance")
public class Rating implements java.io.Serializable {

	private RatingId id;
	private Account accountById;
	private Account accountByUserId;
	private Integer rate;
	private Serializable cmt;

	public Rating() {
	}

	public Rating(RatingId id, Account accountById, Account accountByUserId) {
		this.id = id;
		this.accountById = accountById;
		this.accountByUserId = accountByUserId;
	}

	public Rating(RatingId id, Account accountById, Account accountByUserId, Integer rate, Serializable cmt) {
		this.id = id;
		this.accountById = accountById;
		this.accountByUserId = accountByUserId;
		this.rate = rate;
		this.cmt = cmt;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public RatingId getId() {
		return this.id;
	}

	public void setId(RatingId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id", nullable = false, insertable = false, updatable = false)
	public Account getAccountById() {
		return this.accountById;
	}

	public void setAccountById(Account accountById) {
		this.accountById = accountById;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public Account getAccountByUserId() {
		return this.accountByUserId;
	}

	public void setAccountByUserId(Account accountByUserId) {
		this.accountByUserId = accountByUserId;
	}

	@Column(name = "rate")
	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	@Column(name = "cmt")
	public Serializable getCmt() {
		return this.cmt;
	}

	public void setCmt(Serializable cmt) {
		this.cmt = cmt;
	}

}
