package Freelance.bean;
// Generated Jan 7, 2021, 1:26:51 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Pattern;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;
import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;

import com.sun.istack.internal.NotNull;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "dbo", catalog = "freelance")
public class Users implements java.io.Serializable {
	private String defaultDate = "2021-01-01";
	
	private int id;
	private Account account;
	private Serializable hoTen;
	private Date ngaySinh;
	private String email;
	private String sdt;
	private Serializable diaChi;
	private Boolean type;
	private Serializable chucDanh;
	private Serializable gioiThieu;
	private Long thuChi;
	private Serializable avt;
	

	public Users() {
	}

	public Users(Account account) {
		this.account = account;
	}

	public Users(Account account, Serializable hoTen, Date ngaySinh, String email, String sdt,
			Serializable diaChi, Boolean type, Serializable chucDanh, Serializable gioiThieu, Long thuChi, Serializable avt) {
		this.account = account;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.email = email;
		this.sdt = sdt;
		this.diaChi = diaChi;
		this.type = type;
		this.chucDanh = chucDanh;
		this.gioiThieu = gioiThieu;
		this.thuChi = thuChi;
		this.avt = avt;
	}

	


	public Users(Serializable hoTen, String email, Boolean type) {
		super();
		this.hoTen = hoTen;
		this.email = email;
		this.type = type;
		try {
			this.ngaySinh = new SimpleDateFormat("yyyy-MM-dd").parse(defaultDate);
		} catch (ParseException e) {
		}
		this.gioiThieu = "";
		this.chucDanh = "";
		this.thuChi = 0L;
		this.avt = "img/userAvatar/default.jpg";
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "account"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "ho_ten")
	public Serializable getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(Serializable hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_sinh", length = 23)
	@DateTimeFormat(pattern = "yyyy-MM-dd")
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sdt")
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "dia_chi")
	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "type")
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "chuc_danh")
	public Serializable getChucDanh() {
		return this.chucDanh;
	}

	public void setChucDanh(Serializable chucDanh) {
		this.chucDanh = chucDanh;
	}

	@Column(name = "gioi_thieu")
	public Serializable getGioiThieu() {
		return this.gioiThieu;
	}

	public void setGioiThieu(Serializable gioiThieu) {
		this.gioiThieu = gioiThieu;
	}

	@Column(name = "thu_chi")
	public Long getThuChi() {
		return this.thuChi;
	}

	public void setThuChi(Long thuChi) {
		this.thuChi = thuChi;
	}

	@Column(name = "avt")
	public Serializable getAvt() {
		return this.avt;
	}

	public void setAvt(Serializable avt) {
		this.avt = avt;
	}

}
