package Freelance1;
// Generated Jan 11, 2021, 8:21:37 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FavoritesId generated by hbm2java
 */
@Embeddable
public class FavoritesId implements java.io.Serializable {

	private Integer userId;
	private Integer jobId;

	public FavoritesId() {
	}

	public FavoritesId(Integer userId, Integer jobId) {
		this.userId = userId;
		this.jobId = jobId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "job_id")
	public Integer getJobId() {
		return this.jobId;
	}

	public void setJobId(Integer jobId) {
		this.jobId = jobId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FavoritesId))
			return false;
		FavoritesId castOther = (FavoritesId) other;

		return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
				&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
				&& ((this.getJobId() == castOther.getJobId()) || (this.getJobId() != null
						&& castOther.getJobId() != null && this.getJobId().equals(castOther.getJobId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		result = 37 * result + (getJobId() == null ? 0 : this.getJobId().hashCode());
		return result;
	}

}
