package Freelance1;
// Generated Jan 11, 2021, 8:21:37 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * JobsUserId generated by hbm2java
 */
@Embeddable
public class JobsUserId implements java.io.Serializable {

	private int jobId;
	private int userId;

	public JobsUserId() {
	}

	public JobsUserId(int jobId, int userId) {
		this.jobId = jobId;
		this.userId = userId;
	}

	@Column(name = "job_id", nullable = false)
	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(int jobId) {
		this.jobId = jobId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof JobsUserId))
			return false;
		JobsUserId castOther = (JobsUserId) other;

		return (this.getJobId() == castOther.getJobId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getJobId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
