package Freelance1;
// Generated Jan 11, 2021, 8:21:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jobs generated by hbm2java
 */
@Entity
@Table(name = "jobs", schema = "dbo", catalog = "freelance")
public class Jobs implements java.io.Serializable {

	private Integer id;
	private Account account;
	private JobCagetory jobCagetory;
	private Serializable ten;
	private String thongTin;
	private Date hanChot;
	private Long nganSachTu;
	private Long nganSachDen;
	private Boolean hoanThanh;
	private Set<JobsUser> jobsUsers = new HashSet<JobsUser>(0);
	private Set<JobsSkill> jobsSkills = new HashSet<JobsSkill>(0);
	private Set<JobsSkill> jobsSkills_1 = new HashSet<JobsSkill>(0);
	private Set<Favorites> favoriteses = new HashSet<Favorites>(0);
	private Set<Favorites> favoriteses_1 = new HashSet<Favorites>(0);
	private Set<Favorites> favoriteses_2 = new HashSet<Favorites>(0);
	private Set<JobsSkill> jobsSkills_2 = new HashSet<JobsSkill>(0);
	private Set<JobsUser> jobsUsers_1 = new HashSet<JobsUser>(0);
	private Set<JobsUser> jobsUsers_2 = new HashSet<JobsUser>(0);

	public Jobs() {
	}

	public Jobs(Account account, JobCagetory jobCagetory, Serializable ten, String thongTin, Date hanChot,
			Long nganSachTu, Long nganSachDen, Boolean hoanThanh, Set<JobsUser> jobsUsers, Set<JobsSkill> jobsSkills,
			Set<JobsSkill> jobsSkills_1, Set<Favorites> favoriteses, Set<Favorites> favoriteses_1,
			Set<Favorites> favoriteses_2, Set<JobsSkill> jobsSkills_2, Set<JobsUser> jobsUsers_1,
			Set<JobsUser> jobsUsers_2) {
		this.account = account;
		this.jobCagetory = jobCagetory;
		this.ten = ten;
		this.thongTin = thongTin;
		this.hanChot = hanChot;
		this.nganSachTu = nganSachTu;
		this.nganSachDen = nganSachDen;
		this.hoanThanh = hoanThanh;
		this.jobsUsers = jobsUsers;
		this.jobsSkills = jobsSkills;
		this.jobsSkills_1 = jobsSkills_1;
		this.favoriteses = favoriteses;
		this.favoriteses_1 = favoriteses_1;
		this.favoriteses_2 = favoriteses_2;
		this.jobsSkills_2 = jobsSkills_2;
		this.jobsUsers_1 = jobsUsers_1;
		this.jobsUsers_2 = jobsUsers_2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ntd_id")
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loai_cong_viec")
	public JobCagetory getJobCagetory() {
		return this.jobCagetory;
	}

	public void setJobCagetory(JobCagetory jobCagetory) {
		this.jobCagetory = jobCagetory;
	}

	@Column(name = "ten")
	public Serializable getTen() {
		return this.ten;
	}

	public void setTen(Serializable ten) {
		this.ten = ten;
	}

	@Column(name = "thong_tin")
	public String getThongTin() {
		return this.thongTin;
	}

	public void setThongTin(String thongTin) {
		this.thongTin = thongTin;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "han_chot", length = 23)
	public Date getHanChot() {
		return this.hanChot;
	}

	public void setHanChot(Date hanChot) {
		this.hanChot = hanChot;
	}

	@Column(name = "ngan_sach_tu")
	public Long getNganSachTu() {
		return this.nganSachTu;
	}

	public void setNganSachTu(Long nganSachTu) {
		this.nganSachTu = nganSachTu;
	}

	@Column(name = "ngan_sach_den")
	public Long getNganSachDen() {
		return this.nganSachDen;
	}

	public void setNganSachDen(Long nganSachDen) {
		this.nganSachDen = nganSachDen;
	}

	@Column(name = "hoan_thanh")
	public Boolean getHoanThanh() {
		return this.hoanThanh;
	}

	public void setHoanThanh(Boolean hoanThanh) {
		this.hoanThanh = hoanThanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsUser> getJobsUsers() {
		return this.jobsUsers;
	}

	public void setJobsUsers(Set<JobsUser> jobsUsers) {
		this.jobsUsers = jobsUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsSkill> getJobsSkills() {
		return this.jobsSkills;
	}

	public void setJobsSkills(Set<JobsSkill> jobsSkills) {
		this.jobsSkills = jobsSkills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsSkill> getJobsSkills_1() {
		return this.jobsSkills_1;
	}

	public void setJobsSkills_1(Set<JobsSkill> jobsSkills_1) {
		this.jobsSkills_1 = jobsSkills_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<Favorites> getFavoriteses() {
		return this.favoriteses;
	}

	public void setFavoriteses(Set<Favorites> favoriteses) {
		this.favoriteses = favoriteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<Favorites> getFavoriteses_1() {
		return this.favoriteses_1;
	}

	public void setFavoriteses_1(Set<Favorites> favoriteses_1) {
		this.favoriteses_1 = favoriteses_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<Favorites> getFavoriteses_2() {
		return this.favoriteses_2;
	}

	public void setFavoriteses_2(Set<Favorites> favoriteses_2) {
		this.favoriteses_2 = favoriteses_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsSkill> getJobsSkills_2() {
		return this.jobsSkills_2;
	}

	public void setJobsSkills_2(Set<JobsSkill> jobsSkills_2) {
		this.jobsSkills_2 = jobsSkills_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsUser> getJobsUsers_1() {
		return this.jobsUsers_1;
	}

	public void setJobsUsers_1(Set<JobsUser> jobsUsers_1) {
		this.jobsUsers_1 = jobsUsers_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jobs")
	public Set<JobsUser> getJobsUsers_2() {
		return this.jobsUsers_2;
	}

	public void setJobsUsers_2(Set<JobsUser> jobsUsers_2) {
		this.jobsUsers_2 = jobsUsers_2;
	}

}
