package Freelance1;
// Generated Jan 11, 2021, 8:21:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * RatingFa generated by hbm2java
 */
@Entity
@Table(name = "ratingFa", schema = "dbo", catalog = "freelance")
public class RatingFa implements java.io.Serializable {

	private int id;
	private Account account;
	private Integer rate;
	private Serializable cmt;

	public RatingFa() {
	}

	public RatingFa(Account account) {
		this.account = account;
	}

	public RatingFa(Account account, Integer rate, Serializable cmt) {
		this.account = account;
		this.rate = rate;
		this.cmt = cmt;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "account"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "rate")
	public Integer getRate() {
		return this.rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

	@Column(name = "cmt")
	public Serializable getCmt() {
		return this.cmt;
	}

	public void setCmt(Serializable cmt) {
		this.cmt = cmt;
	}

}
