package Freelance1;
// Generated Jan 11, 2021, 8:21:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Skills generated by hbm2java
 */
@Entity
@Table(name = "skills", schema = "dbo", catalog = "freelance")
public class Skills implements java.io.Serializable {

	private Integer id;
	private Serializable skill;
	private Set<JobsSkill> jobsSkills = new HashSet<JobsSkill>(0);
	private Set<JobsSkill> jobsSkills_1 = new HashSet<JobsSkill>(0);
	private Set<UserSkill> userSkills = new HashSet<UserSkill>(0);
	private Set<UserSkill> userSkills_1 = new HashSet<UserSkill>(0);
	private Set<UserSkill> userSkills_2 = new HashSet<UserSkill>(0);
	private Set<JobsSkill> jobsSkills_2 = new HashSet<JobsSkill>(0);

	public Skills() {
	}

	public Skills(Serializable skill, Set<JobsSkill> jobsSkills, Set<JobsSkill> jobsSkills_1, Set<UserSkill> userSkills,
			Set<UserSkill> userSkills_1, Set<UserSkill> userSkills_2, Set<JobsSkill> jobsSkills_2) {
		this.skill = skill;
		this.jobsSkills = jobsSkills;
		this.jobsSkills_1 = jobsSkills_1;
		this.userSkills = userSkills;
		this.userSkills_1 = userSkills_1;
		this.userSkills_2 = userSkills_2;
		this.jobsSkills_2 = jobsSkills_2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "skill")
	public Serializable getSkill() {
		return this.skill;
	}

	public void setSkill(Serializable skill) {
		this.skill = skill;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<JobsSkill> getJobsSkills() {
		return this.jobsSkills;
	}

	public void setJobsSkills(Set<JobsSkill> jobsSkills) {
		this.jobsSkills = jobsSkills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<JobsSkill> getJobsSkills_1() {
		return this.jobsSkills_1;
	}

	public void setJobsSkills_1(Set<JobsSkill> jobsSkills_1) {
		this.jobsSkills_1 = jobsSkills_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<UserSkill> getUserSkills() {
		return this.userSkills;
	}

	public void setUserSkills(Set<UserSkill> userSkills) {
		this.userSkills = userSkills;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<UserSkill> getUserSkills_1() {
		return this.userSkills_1;
	}

	public void setUserSkills_1(Set<UserSkill> userSkills_1) {
		this.userSkills_1 = userSkills_1;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<UserSkill> getUserSkills_2() {
		return this.userSkills_2;
	}

	public void setUserSkills_2(Set<UserSkill> userSkills_2) {
		this.userSkills_2 = userSkills_2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "skills")
	public Set<JobsSkill> getJobsSkills_2() {
		return this.jobsSkills_2;
	}

	public void setJobsSkills_2(Set<JobsSkill> jobsSkills_2) {
		this.jobsSkills_2 = jobsSkills_2;
	}

}
