package Freelance1;
// Generated Jan 11, 2021, 8:21:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "dbo", catalog = "freelance")
public class Users implements java.io.Serializable {

	private int id;
	private Account account;
	private Serializable hoTen;
	private Date ngaySinh;
	private Serializable email;
	private Integer sdt;
	private Serializable diaChi;
	private Boolean type;
	private Serializable chucDanh;
	private String gioiThieu;
	private Long thuChi;
	private Serializable avt;

	public Users() {
	}

	public Users(Account account) {
		this.account = account;
	}

	public Users(Account account, Serializable hoTen, Date ngaySinh, Serializable email, Integer sdt,
			Serializable diaChi, Boolean type, Serializable chucDanh, String gioiThieu, Long thuChi, Serializable avt) {
		this.account = account;
		this.hoTen = hoTen;
		this.ngaySinh = ngaySinh;
		this.email = email;
		this.sdt = sdt;
		this.diaChi = diaChi;
		this.type = type;
		this.chucDanh = chucDanh;
		this.gioiThieu = gioiThieu;
		this.thuChi = thuChi;
		this.avt = avt;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "account"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@Column(name = "ho_ten")
	public Serializable getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(Serializable hoTen) {
		this.hoTen = hoTen;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngay_sinh", length = 23)
	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	@Column(name = "email")
	public Serializable getEmail() {
		return this.email;
	}

	public void setEmail(Serializable email) {
		this.email = email;
	}

	@Column(name = "sdt")
	public Integer getSdt() {
		return this.sdt;
	}

	public void setSdt(Integer sdt) {
		this.sdt = sdt;
	}

	@Column(name = "dia_chi")
	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	@Column(name = "type")
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "chuc_danh")
	public Serializable getChucDanh() {
		return this.chucDanh;
	}

	public void setChucDanh(Serializable chucDanh) {
		this.chucDanh = chucDanh;
	}

	@Column(name = "gioi_thieu")
	public String getGioiThieu() {
		return this.gioiThieu;
	}

	public void setGioiThieu(String gioiThieu) {
		this.gioiThieu = gioiThieu;
	}

	@Column(name = "thu_chi")
	public Long getThuChi() {
		return this.thuChi;
	}

	public void setThuChi(Long thuChi) {
		this.thuChi = thuChi;
	}

	@Column(name = "avt")
	public Serializable getAvt() {
		return this.avt;
	}

	public void setAvt(Serializable avt) {
		this.avt = avt;
	}

}
